# Generated by Django 2.2.8 on 2021-08-13 09:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_yubin', '0005_auto_20181128_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bcc_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None, verbose_name='BCC'),
        ),
        migrations.AddField(
            model_name='message',
            name='cc_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None, verbose_name='CC'),
        ),
    ]
